import os
q = chr(34)

def w(path, lines):
    with open(path, "w", encoding="utf-8") as f:
        for line in lines:
            f.write(line + "\n")
    print("Wrote: " + os.path.basename(path))

kb = []
kb.append("import React, { useState } from " + q + "react" + q + ";")
kb.append("import { Card, Typography, Input, Button, Upload, Table, Tag, Space, Modal, Tabs, Popconfirm, Spin, Empty, Descriptions } from " + q + "antd" + q + ";")
kb.append("import { SearchOutlined, UploadOutlined, DeleteOutlined, DatabaseOutlined, LinkOutlined } from " + q + "@ant-design/icons" + q + ";")
kb.append("import { useKnowledgeSearch, useKnowledgeDocs, useKnowledgeDoc, useKnowledgeStats, useUploadDocument, useIndexWebContent, useDeleteDocument } from " + q + "../../hooks/useKnowledge" + q + ";")
kb.append("import { DOC_TYPE_LABELS, type KnowledgeDocument } from " + q + "../../api/knowledge" + q + ";")
kb.append("")
kb.append("const { Title, Paragraph, Text } = Typography;")
kb.append("const { TextArea } = Input;")
kb.append("")
kb.append("const TYPE_COLORS: Record<string, string> = { pdf: " + q + "red" + q + ", markdown: " + q + "blue" + q + ", txt: " + q + "default" + q + ", code: " + q + "green" + q + ", web: " + q + "orange" + q + " };")
kb.append("")
kb.append("const KnowledgeBase: React.FC = () => {")
kb.append("  const [searchQuery, setSearchQuery] = useState(" + q + q + ");")
kb.append("  const [activeQuery, setActiveQuery] = useState(" + q + q + ");")
kb.append("  const [viewDocId, setViewDocId] = useState<string | null>(null);")
kb.append("  const [webModalOpen, setWebModalOpen] = useState(false);")
kb.append("  const [webContent, setWebContent] = useState(" + q + q + ");")
kb.append("  const [webFilename, setWebFilename] = useState(" + q + q + ");")
kb.append("  const { data: searchResults, isLoading: searchLoading } = useKnowledgeSearch(activeQuery);")
kb.append("  const { data: docsData } = useKnowledgeDocs();")
kb.append("  const { data: statsData } = useKnowledgeStats();")
kb.append("  const { data: viewDoc } = useKnowledgeDoc(viewDocId || " + q + q + ");")
kb.append("  const uploadMut = useUploadDocument();")
kb.append("  const webMut = useIndexWebContent();")
kb.append("  const deleteMut = useDeleteDocument();")
kb.append("")
kb.append("  const handleSearch = () => setActiveQuery(searchQuery);")
kb.append("  const handleUpload = (file: File) => { uploadMut.mutate(file); return false; };")
kb.append("  const handleWebSubmit = () => { webMut.mutate({ content: webContent, filename: webFilename }); setWebModalOpen(false); setWebContent(" + q + q + "); setWebFilename(" + q + q + "); };")
kb.append("")
kb.append("  const columns = [")
kb.append("    { title: " + q + "Title" + q + ", dataIndex: " + q + "title" + q + ", key: " + q + "title" + q + ", ellipsis: true },")
kb.append("    { title: " + q + "Type" + q + ", dataIndex: " + q + "doc_type" + q + ", width: 100, render: (t: string) => <Tag color={TYPE_COLORS[t]}>{DOC_TYPE_LABELS[t] || t}</Tag> },")
kb.append("    { title: " + q + "Chunks" + q + ", dataIndex: " + q + "chunk_count" + q + ", width: 80 },")
kb.append("    { title: " + q + "Tags" + q + ", dataIndex: " + q + "tags" + q + ", width: 200, render: (tags: string[]) => tags?.map((t: string) => <Tag key={t}>{t}</Tag>) || null },")
kb.append("    { title: " + q + "Actions" + q + ", key: " + q + "actions" + q + ", width: 120, render: (_: unknown, r: KnowledgeDocument) => (")
kb.append("      <Space><Button size=" + q + "small" + q + " onClick={() => setViewDocId(r.id)}>View</Button>")
kb.append("      <Popconfirm title=" + q + "Delete?" + q + " onConfirm={() => deleteMut.mutate(r.id)}><Button size=" + q + "small" + q + " danger icon={<DeleteOutlined />} /></Popconfirm></Space>) },")
kb.append("  ];")
kb.append("")
kb.append("  return (")
kb.append("    <div style={{ padding: 24, maxWidth: 1200, margin: " + q + "0 auto" + q + " }}>")
kb.append("      <Title level={2}><DatabaseOutlined /> Knowledge Base</Title>")
kb.append("      <Paragraph type=" + q + "secondary" + q + ">Upload documents, index web content, and search your personal knowledge.</Paragraph>")
kb.append("      <Tabs defaultActiveKey=" + q + "docs" + q + " items={[")
kb.append("        { key: " + q + "docs" + q + ", label: " + q + "Documents" + q + ", children: (docsData?.documents || []).length === 0 ? <Empty description=" + q + "No documents yet" + q + " /> : (")
kb.append("          <Table rowKey=" + q + "id" + q + " dataSource={docsData?.documents || []} columns={columns} size=" + q + "middle" + q + " onRow={(r) => ({ onClick: () => setViewDocId(r.id), style: { cursor: " + q + "pointer" + q + " } })} pagination={{ pageSize: 15 }} />) },")
kb.append("        { key: " + q + "search" + q + ", label: " + q + "Search" + q + ", children: (<>")
kb.append("          <Space style={{ marginBottom: 16 }} wrap>")
kb.append("            <Input.Search placeholder=" + q + "Search knowledge..." + q + " value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} onSearch={handleSearch} style={{ width: 320 }} />")
kb.append("            <Upload beforeUpload={handleUpload} showUploadList={false}><Button icon={<UploadOutlined />}>Upload File</Button></Upload>")
kb.append("            <Button icon={<LinkOutlined />} onClick={() => setWebModalOpen(true)}>Web Content</Button>")
kb.append("          </Space>")
kb.append("          {searchLoading ? <Spin /> : (searchResults?.results || []).length === 0 ? <Empty /> : (")
kb.append("            <Table rowKey=" + q + "chunk_id" + q + " dataSource={searchResults?.results || []} columns={[")
kb.append("              { title: " + q + "Title" + q + ", dataIndex: " + q + "title" + q + ", ellipsis: true },")
kb.append("              { title: " + q + "Content" + q + ", dataIndex: " + q + "content" + q + ", ellipsis: true, render: (t: string) => t?.slice(0, 200) },")
kb.append("              { title: " + q + "Score" + q + ", dataIndex: " + q + "score" + q + ", width: 80, render: (v: number) => v?.toFixed(2) },")
kb.append("            ]} size=" + q + "middle" + q + " pagination={{ pageSize: 15 }} />)}")
kb.append("        </>) },")
kb.append("      ]} />")
kb.append("      <Modal title=" + q + "Document Detail" + q + " open={!!viewDocId} onCancel={() => setViewDocId(null)} footer={null} width={700}>")
kb.append("        {viewDoc?.document && (<Descriptions column={1} bordered size=" + q + "small" + q + ">")
kb.append("          <Descriptions.Item label=" + q + "Title" + q + ">{viewDoc.document.title}</Descriptions.Item>")
kb.append("          <Descriptions.Item label=" + q + "Type" + q + "><Tag color={TYPE_COLORS[viewDoc.document.doc_type]}>{DOC_TYPE_LABELS[viewDoc.document.doc_type]}</Tag></Descriptions.Item>")
kb.append("          <Descriptions.Item label=" + q + "Tags" + q + ">{viewDoc.document.tags?.map((t: string) => <Tag key={t}>{t}</Tag>)}</Descriptions.Item>")
kb.append("          <Descriptions.Item label=" + q + "Summary" + q + ">{viewDoc.document.summary}</Descriptions.Item>")
kb.append("          <Descriptions.Item label=" + q + "Chunks" + q + ">{(viewDoc.chunks || []).length}</Descriptions.Item>")
kb.append("        </Descriptions>)}")
kb.append("      </Modal>")
kb.append("      <Modal title=" + q + "Add Web Content" + q + " open={webModalOpen} onOk={handleWebSubmit} onCancel={() => setWebModalOpen(false)}>")
kb.append("        <TextArea rows={6} placeholder=" + q + "Paste content here..." + q + " value={webContent} onChange={(e) => setWebContent(e.target.value)} style={{ marginBottom: 12 }} />")
kb.append("        <Input placeholder=" + q + "Optional filename" + q + " value={webFilename} onChange={(e) => setWebFilename(e.target.value)} />")
kb.append("      </Modal>")
kb.append("    </div>")
kb.append("  );")
kb.append("};")
kb.append("")
kb.append("export default KnowledgeBase;")

w(r"E:\半自动工作台\frontend\src\pages\KnowledgeBase\index.tsx", kb)
print("KnowledgeBase page done")
