
import os
q = chr(34)  # double quote

def w(path, lines):
    with open(path, "w", encoding="utf-8") as f:
        for line in lines:
            f.write(line + "\n")
    print("Wrote: " + os.path.basename(path) + " (" + str(len(lines)) + " lines)")

t = []
t.append(q + q + q)
t.append("Phase 5.4 tests - Knowledge Parser, Indexer, Retriever, API.")
t.append(q + q + q)
t.append("import io")
t.append("import pytest")
t.append("from httpx import AsyncClient, ASGITransport")
t.append("")
t.append("from app.knowledge.parser import KnowledgeParser, ParsedKnowledge, DocumentType")
t.append("from app.knowledge.indexer import KnowledgeIndexer, KnowledgeDocument, KnowledgeChunk")
t.append("from app.knowledge.retriever import KnowledgeRetriever")
t.append("from app.main import app")
t.append("")
t.append("")
t.append("class TestDocumentType:")
t.append("    def test_all_types(self):")
t.append("        assert DocumentType.PDF == " + q + "pdf" + q)
t.append("        assert DocumentType.MARKDOWN == " + q + "markdown" + q)
t.append("        assert DocumentType.TXT == " + q + "txt" + q)
t.append("        assert DocumentType.CODE == " + q + "code" + q)
t.append("        assert DocumentType.WEB == " + q + "web" + q)
t.append("")
t.append("    def test_type_values(self):")
t.append("        types = [t.value for t in DocumentType]")
t.append("        assert " + q + "pdf" + q + " in types")
t.append("        assert " + q + "markdown" + q + " in types")
t.append("")
t.append("")
t.append("class TestKnowledgeParser:")
t.append("    def test_detect_markdown(self):")
t.append("        parser = KnowledgeParser()")
t.append("        parsed = parser.parse(" + q + "# Hello\\n\\ncontent" + q + ", " + q + "test.md" + q + ")")
t.append("        assert parsed.doc_type == DocumentType.MARKDOWN")
t.append("")
t.append("    def test_detect_code(self):")
t.append("        parser = KnowledgeParser()")
t.append("        parsed = parser.parse(" + q + "def foo(): pass" + q + ", " + q + "test.py" + q + ")")
t.append("        assert parsed.doc_type == DocumentType.CODE")
t.append("")
t.append("    def test_detect_txt(self):")
t.append("        parser = KnowledgeParser()")
t.append("        parsed = parser.parse(" + q + "plain text" + q + ", " + q + "test.txt" + q + ")")
t.append("        assert parsed.doc_type == DocumentType.TXT")
t.append("")
t.append("    def test_detect_pdf(self):")
t.append("        parser = KnowledgeParser()")
t.append("        parsed = parser.parse(" + q + "dummy" + q + ", " + q + "test.pdf" + q + ")")
t.append("        assert parsed.doc_type == DocumentType.PDF")
t.append("")
t.append("    def test_extract_title_from_filename(self):")
t.append("        parser = KnowledgeParser()")
t.append("        parsed = parser.parse(" + q + "content" + q + ", " + q + "my_awesome_note.md" + q + ")")
t.append("        assert parsed.title == " + q + "my awesome note" + q)
t.append("")
t.append("    def test_extract_title_from_heading(self):")
t.append("        parser = KnowledgeParser()")
t.append("        parsed = parser.parse(" + q + "# AI Research Guide\\n\\ncontent" + q + ")")
t.append("        assert parsed.title == " + q + "AI Research Guide" + q)
t.append("")
t.append("    def test_extract_title_default(self):")
t.append("        parser = KnowledgeParser()")
t.append("        parsed = parser.parse(" + q + q + ", " + q + q + ")")
t.append("        assert parsed.title == " + q + "Untitled" + q)
t.append("")
t.append("    def test_chunk_content(self):")
t.append("        parser = KnowledgeParser()")
t.append("        long_text = " + q + "Paragraph one.\\n" + q + " * 50")
t.append("        parsed = parser.parse(long_text, " + q + "test.txt" + q + ")")
t.append("        assert len(parsed.chunks) > 1")
t.append("")
t.append("    def test_chunk_single(self):")
t.append("        parser = KnowledgeParser()")
t.append("        parsed = parser.parse(" + q + "short content" + q + ", " + q + "test.txt" + q + ")")
t.append("        assert len(parsed.chunks) == 1")
t.append("")
t.append("    def test_extract_tags_python(self):")
t.append("        parser = KnowledgeParser()")
t.append("        parsed = parser.parse(" + q + "Using python and pandas for data analysis" + q + ", " + q + "test.txt" + q + ")")
t.append("        assert " + q + "python" + q + " in parsed.tags")
t.append("")
t.append("    def test_extract_tags_code(self):")
t.append("        parser = KnowledgeParser()")
t.append("        parsed = parser.parse(" + q + "def foo(): pass" + q + ", " + q + "test.py" + q + ")")
t.append("        assert " + q + "code" + q + " in parsed.tags")
t.append("")
t.append("    def test_generate_summary(self):")
t.append("        parser = KnowledgeParser()")
t.append("        parsed = parser.parse(" + q + "This is a document with enough content to generate a meaningful summary for testing purposes. " + q + " * 3, " + q + "test.txt" + q + ")")
t.append("        assert len(parsed.summary) > 0")
t.append("")
t.append("    def test_html_cleaning(self):")
t.append("        parser = KnowledgeParser()")
t.append("        parsed = parser.parse(" + q + "<html><body><p>Hello World</p><script>alert(1)</script></body></html>" + q + ", " + q + "page.html" + q + ")")
t.append("        assert " + q + "Hello World" + q + " in parsed.content")
t.append("        assert " + q + "alert" + q + " not in parsed.content")
t.append("")
t.append("    def test_html_entity_decoding(self):")
t.append("        parser = KnowledgeParser()")
t.append("        parsed = parser.parse(" + q + "<p>a &amp; b &lt; c</p>" + q + ", " + q + "test.html" + q + ")")
t.append("        assert " + q + "a & b < c" + q + " in parsed.content")
t.append("")
t.append("    def test_metadata_set(self):")
t.append("        parser = KnowledgeParser()")
t.append("        parsed = parser.parse(" + q + "content" + q + ", " + q + "file.md" + q + ", " + q + "https://example.com" + q + ")")
t.append("        assert parsed.metadata[" + q + "filename" + q + "] == " + q + "file.md" + q)
t.append("        assert parsed.metadata[" + q + "source_url" + q + "] == " + q + "https://example.com" + q)
t.append("")
t.append("")
t.append("class TestKnowledgeIndexer:")
t.append("    def test_index_content(self):")
t.append("        idx = KnowledgeIndexer()")
t.append("        doc = idx.index(" + q + "Python async programming guide" + q + ", " + q + "guide.md" + q + ")")
t.append("        assert doc.doc_type == " + q + "markdown" + q)
t.append("")
t.append("    def test_index_creates_chunks(self):")
t.append("        idx = KnowledgeIndexer()")
t.append("        long_text = " + q + "Paragraph one.\\n\\n" + q + " * 20")
t.append("        doc = idx.index(long_text, " + q + "long.md" + q + ")")
t.append("        assert doc.chunk_count > 1")
t.append("")
t.append("    def test_get_document(self):")
t.append("        idx = KnowledgeIndexer()")
t.append("        doc = idx.index(" + q + "test content" + q + ", " + q + "test.txt" + q + ")")
t.append("        retrieved = idx.get_document(doc.id)")
t.append("        assert retrieved is not None")
t.append("")
t.append("    def test_get_nonexistent_document(self):")
t.append("        idx = KnowledgeIndexer()")
t.append("        assert idx.get_document(" + q + "nonexistent" + q + ") is None")
t.append("")
t.append("    def test_get_chunks(self):")
t.append("        idx = KnowledgeIndexer()")
t.append("        doc = idx.index(" + q + "a\\n\\nb\\n\\nc\\n\\nd\\n\\ne\\n\\nf\\n\\ng" + q + ", " + q + "test.md" + q + ")")
t.append("        chunks = idx.get_chunks(doc.id)")
t.append("        assert len(chunks) > 0")
t.append("")
t.append("    def test_list_documents(self):")
t.append("        idx = KnowledgeIndexer()")
t.append("        idx.index(" + q + "doc1" + q + ", " + q + "a.txt" + q + ")")
t.append("        idx.index(" + q + "doc2" + q + ", " + q + "b.py" + q + ")")
t.append("        docs = idx.list_documents()")
t.append("        assert len(docs) >= 2")
t.append("")
t.append("    def test_list_by_type(self):")
t.append("        idx = KnowledgeIndexer()")
t.append("        idx.index(" + q + "a" + q + ", " + q + "a.txt" + q + ")")
t.append("        idx.index(" + q + "b" + q + ", " + q + "b.py" + q + ")")
t.append("        idx.index(" + q + "c" + q + ", " + q + "c.md" + q + ")")
t.append("        docs = idx.list_documents(doc_type=" + q + "markdown" + q + ")")
t.append("        assert len(docs) == 1")
t.append("")
t.append("    def test_delete_document(self):")
t.append("        idx = KnowledgeIndexer()")
t.append("        doc = idx.index(" + q + "test" + q + ", " + q + "test.txt" + q + ")")
t.append("        assert idx.delete_document(doc.id) is True")
t.append("        assert idx.get_document(doc.id) is None")
t.append("")
t.append("    def test_delete_nonexistent(self):")
t.append("        idx = KnowledgeIndexer()")
t.append("        assert idx.delete_document(" + q + "nonexistent" + q + ") is False")
t.append("")
t.append("    def test_search_finds_content(self):")
t.append("        idx = KnowledgeIndexer()")
t.append("        idx.index(" + q + "artificial intelligence and machine learning" + q + ", " + q + "ai.md" + q + ")")
t.append("        results = idx.search(" + q + "artificial intelligence" + q + ")")
t.append("        assert len(results) >= 1")
t.append("")
t.append("    def test_search_no_match(self):")
t.append("        idx = KnowledgeIndexer()")
t.append("        idx.index(" + q + "python code" + q + ", " + q + "test.py" + q + ")")
t.append("        results = idx.search(" + q + "cooking recipes" + q + ")")
t.append("        assert len(results) == 0")
t.append("")
t.append("    def test_stats(self):")
t.append("        idx = KnowledgeIndexer()")
t.append("        idx.index(" + q + "a" + q + ", " + q + "a.txt" + q + ")")
t.append("        idx.index(" + q + "b" + q + ", " + q + "b.md" + q + ")")
t.append("        stats = idx.get_stats()")
t.append("        assert stats[" + q + "total_documents" + q + "] == 2")
t.append("")
t.append("    def test_clear(self):")
t.append("        idx = KnowledgeIndexer()")
t.append("        idx.index(" + q + "test" + q + ", " + q + "test.txt" + q + ")")
t.append("        idx.clear()")
t.append("        assert idx.get_stats()[" + q + "total_documents" + q + "] == 0")
t.append("")
t.append("")
t.append("class TestKnowledgeRetriever:")
t.append("    def test_search(self):")
t.append("        idx = KnowledgeIndexer()")
t.append("        idx.index(" + q + "Python async best practices" + q + ", " + q + "python.md" + q + ")")
t.append("        retriever = KnowledgeRetriever(idx)")
t.append("        results = retriever.search(" + q + "async" + q + ")")
t.append("        assert len(results) >= 1")
t.append("")
t.append("    def test_search_filter_by_type(self):")
t.append("        idx = KnowledgeIndexer()")
t.append("        idx.index(" + q + "Python code" + q + ", " + q + "test.py" + q + ")")
t.append("        idx.index(" + q + "Markdown notes" + q + ", " + q + "notes.md" + q + ")")
t.append("        retriever = KnowledgeRetriever(idx)")
t.append("        results = retriever.search(" + q + "notes" + q + ", doc_type=" + q + "markdown" + q + ")")
t.append("        assert len(results) >= 1")
t.append("")
t.append("    def test_get_context_for_task(self):")
t.append("        idx = KnowledgeIndexer()")
t.append("        idx.index(" + q + "FastAPI is a modern web framework for Python" + q + ", " + q + "fastapi.md" + q + ")")
t.append("        retriever = KnowledgeRetriever(idx)")
t.append("        ctx = retriever.get_context_for_task(" + q + "build web API" + q + ")")
t.append("        assert " + q + "FastAPI" + q + " in ctx or " + q + "web" + q + " in ctx.lower()")
t.append("")
t.append("    def test_get_context_empty(self):")
t.append("        idx = KnowledgeIndexer()")
t.append("        retriever = KnowledgeRetriever(idx)")
t.append("        ctx = retriever.get_context_for_task(" + q + "nonexistent" + q + ")")
t.append("        assert ctx == " + q + q)
t.append("")
t.append("")
t.append("class TestKnowledgeAPI:")
t.append("    async def test_upload_text_file(self):")
t.append("        async with AsyncClient(transport=ASGITransport(app=app), base_url=" + q + "http://test" + q + ") as c:")
t.append("            resp = await c.post(" + q + "/api/v1/knowledge/upload" + q + ", files={" + q + "file" + q + ": (" + q + "test.txt" + q + ", io.BytesIO(b" + q + "hello world" + q + "), " + q + "text/plain" + q + ")})")
t.append("        assert resp.status_code == 200")
t.append("        data = resp.json()")
t.append("        assert data[" + q + "success" + q + "] is True")
t.append("")
t.append("    async def test_web_content(self):")
t.append("        async with AsyncClient(transport=ASGITransport(app=app), base_url=" + q + "http://test" + q + ") as c:")
t.append("            resp = await c.post(" + q + "/api/v1/knowledge/web" + q + ", json={" + q + "content" + q + ": " + q + "test content" + q + ", " + q + "filename" + q + ": " + q + "test.txt" + q + "})")
t.append("        assert resp.status_code == 200")
t.append("        data = resp.json()")
t.append("        assert data[" + q + "success" + q + "] is True")
t.append("")
t.append("    async def test_search(self):")
t.append("        async with AsyncClient(transport=ASGITransport(app=app), base_url=" + q + "http://test" + q + ") as c:")
t.append("            await c.post(" + q + "/api/v1/knowledge/web" + q + ", json={" + q + "content" + q + ": " + q + "machine learning algorithms" + q + "})")
t.append("            resp = await c.post(" + q + "/api/v1/knowledge/search" + q + ", json={" + q + "query" + q + ": " + q + "machine learning" + q + "})")
t.append("        data = resp.json()")
t.append("        assert data[" + q + "success" + q + "] is True")
t.append("")
t.append("    async def test_list_documents(self):")
t.append("        async with AsyncClient(transport=ASGITransport(app=app), base_url=" + q + "http://test" + q + ") as c:")
t.append("            resp = await c.get(" + q + "/api/v1/knowledge/documents" + q + ")")
t.append("        data = resp.json()")
t.append("        assert data[" + q + "success" + q + "] is True")
t.append("")
t.append("    async def test_get_document_by_id(self):")
t.append("        async with AsyncClient(transport=ASGITransport(app=app), base_url=" + q + "http://test" + q + ") as c:")
t.append("            create = await c.post(" + q + "/api/v1/knowledge/web" + q + ", json={" + q + "content" + q + ": " + q + "findme" + q + "})")
t.append("            doc_id = create.json()[" + q + "document" + q + "][" + q + "id" + q + "]")
t.append("            resp = await c.get(f" + q + "/api/v1/knowledge/documents/{doc_id}" + q + ")")
t.append("        assert resp.json()[" + q + "success" + q + "] is True")
t.append("")
t.append("    async def test_get_nonexistent_document(self):")
t.append("        async with AsyncClient(transport=ASGITransport(app=app), base_url=" + q + "http://test" + q + ") as c:")
t.append("            resp = await c.get(" + q + "/api/v1/knowledge/documents/nonexistent" + q + ")")
t.append("        assert resp.json()[" + q + "success" + q + "] is False")
t.append("")
t.append("    async def test_delete_document(self):")
t.append("        async with AsyncClient(transport=ASGITransport(app=app), base_url=" + q + "http://test" + q + ") as c:")
t.append("            create = await c.post(" + q + "/api/v1/knowledge/web" + q + ", json={" + q + "content" + q + ": " + q + "tobedeleted" + q + "})")
t.append("            doc_id = create.json()[" + q + "document" + q + "][" + q + "id" + q + "]")
t.append("            resp = await c.delete(f" + q + "/api/v1/knowledge/documents/{doc_id}" + q + ")")
t.append("        assert resp.json()[" + q + "success" + q + "] is True")
t.append("")
t.append("    async def test_stats(self):")
t.append("        async with AsyncClient(transport=ASGITransport(app=app), base_url=" + q + "http://test" + q + ") as c:")
t.append("            resp = await c.get(" + q + "/api/v1/knowledge/stats" + q + ")")
t.append("        data = resp.json()")
t.append("        assert data[" + q + "success" + q + "] is True")

w(r"E:\半自动工作台\backend\tests\test_knowledge.py", t)
print("Test file written successfully")

