import os

def w(path, lines):
    with open(path, "w", encoding="utf-8") as f:
        for line in lines:
            f.write(line + "\n")
    print("Wrote: " + os.path.basename(path))

# Frontend Knowledge test
test_lines = [
    "import { describe, it, expect, vi, beforeEach } from " + chr(34) + "vitest" + chr(34) + ";",
    "import { renderHook, waitFor } from " + chr(34) + "@testing-library/react" + chr(34) + ";",
    "import { QueryClient, QueryClientProvider } from " + chr(34) + "@tanstack/react-query" + chr(34) + ";",
    "import React from " + chr(34) + "react" + chr(34) + ";",
    "import apiClient from " + chr(34) + "../api/client" + chr(34) + ";",
    "import { searchKnowledge, listDocuments, getDocument, deleteDocument, getKnowledgeStats, DOC_TYPES } from " + chr(34) + "../api/knowledge" + chr(34) + ";",
    "import { useKnowledgeDocs } from " + chr(34) + "../hooks/useKnowledge" + chr(34) + ";",
    "",
    "vi.mock(" + chr(34) + "../api/client" + chr(34) + ");",
    "var mockGet = vi.mocked(apiClient.get);",
    "var mockPost = vi.mocked(apiClient.post);",
    "var mockDelete = vi.mocked(apiClient.delete);",
    "beforeEach(function() { vi.clearAllMocks(); });",
    "",
    "function wrapper(obj) { var qc = new QueryClient({ defaultOptions: { queries: { retry: false } } }); return React.createElement(QueryClientProvider, { client: qc }, obj.children); }",
    "",
    "describe(" + chr(34) + "Knowledge API" + chr(34) + ", function() {",
    "  it(" + chr(34) + "searchKnowledge calls POST" + chr(34) + ", async function() {",
    '    mockPost.mockResolvedValue({ data: { success: true } });',
    '    var res = await searchKnowledge("test");',
    "    expect(res.success).toBe(true);",
    "    expect(mockPost).toHaveBeenCalled();",
    "  });",
    "",
    "  it(" + chr(34) + "listDocuments calls GET" + chr(34) + ", async function() {",
    '    mockGet.mockResolvedValue({ data: { success: true, documents: [] } });',
    "    var res = await listDocuments();",
    "    expect(res.success).toBe(true);",
    "    expect(mockGet).toHaveBeenCalled();",
    "  });",
    "",
    "  it(" + chr(34) + "getDocument calls GET with id" + chr(34) + ", async function() {",
    '    mockGet.mockResolvedValue({ data: { success: true } });',
    '    var res = await getDocument("d1");',
    "    expect(res.success).toBe(true);",
    "    expect(mockGet).toHaveBeenCalled();",
    "  });",
    "",
    "  it(" + chr(34) + "deleteDocument calls DELETE" + chr(34) + ", async function() {",
    '    mockDelete.mockResolvedValue({ data: { success: true } });',
    '    var res = await deleteDocument("d1");',
    "    expect(res.success).toBe(true);",
    "    expect(mockDelete).toHaveBeenCalled();",
    "  });",
    "",
    "  it(" + chr(34) + "getKnowledgeStats calls GET" + chr(34) + ", async function() {",
    '    mockGet.mockResolvedValue({ data: { success: true, data: { total_documents: 5 } } });',
    "    var res = await getKnowledgeStats();",
    "    expect(res.success).toBe(true);",
    "  });",
    "",
    "  it(" + chr(34) + "DOC_TYPES has 5 types" + chr(34) + ", function() {",
    "    expect(DOC_TYPES).toHaveLength(5);",
    '    expect(DOC_TYPES).toContain("pdf");',
    '    expect(DOC_TYPES).toContain("markdown");',
    "  });",
    "});",
    "",
    "describe(" + chr(34) + "useKnowledgeDocs hook" + chr(34) + ", function() {",
    "  it(" + chr(34) + "returns data" + chr(34) + ", async function() {",
    '    mockGet.mockResolvedValue({ data: { success: true, documents: [{ id: "1", title: "Test", doc_type: "txt", chunk_count: 2, tags: ["ai"], summary: "s", filename: "t.txt", source_url: "", metadata: {}, created_at: "2026-01-01" }] } });',
    "    var result = renderHook(function() { return useKnowledgeDocs(); }, { wrapper: wrapper });",
    "    await waitFor(function() { return expect(result.result.current.isSuccess).toBe(true); });",
    '    expect(result.result.current.data.documents[0].title).toBe("Test");',
    "  });",
    "});",
    "",
    "describe(" + chr(34) + "Knowledge error handling" + chr(34) + ", function() {",
    "  it(" + chr(34) + "handles search error" + chr(34) + ", async function() {",
    '    mockPost.mockRejectedValue(new Error("Fail"));',
    '    await expect(searchKnowledge("test")).rejects.toThrow("Fail");',
    "  });",
    "",
    "  it(" + chr(34) + "handles empty results" + chr(34) + ", async function() {",
    '    mockPost.mockResolvedValue({ data: { success: true, results: [] } });',
    '    var res = await searchKnowledge("nothing");',
    "    expect(res.results).toEqual([]);",
    "  });",
    "});",
]

w(r"E:\半自动工作台\frontend\src\__tests__\knowledge.test.ts", test_lines)
print("All frontend tests written")
